image: php:7.1.1

pipelines:
  branches:
    master:
      - step:
          caches:
            - composer
          script:
            - apt-get update && apt-get install
            - apt-get -qq install git-ftp
            - git ftp push --user tuulscom --passwd 8dp11Kg3Ax -v mars.rubyhost.com.br/public_html